version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - pgdata:/var/lib/postgresql/data

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_STARTPOLLERS: 5
      ZBX_STARTTRAPPERS: 2
    depends_on:
      - postgres
    ports:
      - "10051:10051"  # Zabbix trapper port

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: UTC
    depends_on:
      - postgres
      - zabbix-server
    ports:
      - "8080:8080"  # Web UI

  grafana:
    image: grafana/grafana:10.4.3
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/grafana/dashboards_json:/var/lib/grafana/dashboards
    depends_on:
      - zabbix-web

  snmpsim:
    image: polinux/snmpd:latest
    restart: unless-stopped
    environment:
      - SNMP_ROCOMMUNITY=public
    ports:
      - "161:161/udp"


volumes:
  pgdata:


